"""Grain-aware transformation, grouping, and joining for Chapter 12."""
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from analytics_foundations.datasets import PROJECT_ROOT, load_chapter_12_data

GRAIN_LEDGER = {
    "transactions": "transaction",
    "daily_revenue": "location-day",
    "labor_daily": "location-day",
    "daily_metrics": "location-day",
    "location_summary": "location",
}


def validate_source_keys(transactions: pd.DataFrame, locations: pd.DataFrame, labor_daily: pd.DataFrame) -> None:
    """Enforce uniqueness implied by each source table's stated grain."""
    if not transactions["transaction_id"].is_unique:
        raise ValueError("transaction_id must identify one transaction")
    if not locations["location_id"].is_unique:
        raise ValueError("location_id must identify one location")
    if labor_daily.duplicated(["location_id", "date"]).any():
        raise ValueError("(location_id, date) must identify one labor observation")


def attach_locations(transactions: pd.DataFrame, locations: pd.DataFrame) -> tuple[pd.DataFrame, int]:
    """Perform and audit a row-preserving many-to-one metadata join."""
    merged = transactions.merge(locations, on="location_id", how="left", validate="many_to_one", indicator=True)
    unmatched = int(merged["_merge"].ne("both").sum())
    return merged.drop(columns="_merge"), unmatched


def demonstrate_labor_duplication(transactions: pd.DataFrame, labor_daily: pd.DataFrame) -> tuple[pd.DataFrame, float]:
    """Isolate the unsafe summation caused by repeated daily labor values."""
    repeated = transactions.merge(labor_daily, on=["location_id", "date"], how="left", validate="many_to_one")
    return repeated, float(repeated["labor_hours"].sum())


def aggregate_daily_revenue(transactions: pd.DataFrame) -> pd.DataFrame:
    """Deliberately change transaction grain to one location-day."""
    return (transactions.groupby(["location_id", "date"], as_index=False)
            .agg(revenue=("net_revenue", "sum"), transactions=("transaction_id", "count")))


def build_daily_metrics(daily_revenue: pd.DataFrame, labor_daily: pd.DataFrame) -> pd.DataFrame:
    """Join compatible location-day grains with an executable cardinality claim."""
    daily = daily_revenue.merge(labor_daily, on=["location_id", "date"], how="left", validate="one_to_one", indicator=True)
    if daily["_merge"].ne("both").any():
        raise ValueError("every revenue location-day must have labor evidence")
    return (daily.drop(columns="_merge")
            .assign(revenue_per_labor_hour=lambda x: x.revenue / x.labor_hours,
                    day_of_week=lambda x: x.date.dt.day_name()))


def aggregate_locations(daily: pd.DataFrame, locations: pd.DataFrame) -> pd.DataFrame:
    """Compute ratio of sums at location grain, then attach readable metadata."""
    summary = (daily.groupby("location_id", as_index=False)
               .agg(revenue=("revenue", "sum"), labor_hours=("labor_hours", "sum"), labor_cost=("labor_cost", "sum"), transactions=("transactions", "sum"))
               .assign(revenue_per_labor_hour=lambda x: x.revenue / x.labor_hours))
    return summary.merge(locations, on="location_id", how="left", validate="one_to_one")


def many_to_many_example() -> pd.DataFrame:
    """Return the four combinations generated by a deliberately tiny 2x2 merge."""
    orders = pd.DataFrame({"customer_id": ["C1", "C1"], "order": ["A", "B"]})
    campaigns = pd.DataFrame({"customer_id": ["C1", "C1"], "campaign": ["Email", "SMS"]})
    return orders.merge(campaigns, on="customer_id", validate="many_to_many")


def reconcile(transactions: pd.DataFrame, labor_daily: pd.DataFrame, daily: pd.DataFrame, summary: pd.DataFrame) -> dict[str, bool]:
    """Check that correct grain changes preserve revenue and labor evidence."""
    return {
        "transaction_to_daily_revenue": abs(transactions.net_revenue.sum() - daily.revenue.sum()) < 1e-9,
        "daily_to_location_revenue": abs(daily.revenue.sum() - summary.revenue.sum()) < 1e-9,
        "labor_to_daily": abs(labor_daily.labor_hours.sum() - daily.labor_hours.sum()) < 1e-9,
        "daily_to_location_labor": abs(daily.labor_hours.sum() - summary.labor_hours.sum()) < 1e-9,
    }


def _save(fig, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True); fig.tight_layout(); fig.savefig(path, dpi=150); plt.close(fig); return path


def create_figures(transactions: pd.DataFrame, daily: pd.DataFrame, summary: pd.DataFrame, output_dir: Path) -> list[Path]:
    """Create grain, component-total, and final-rate teaching figures."""
    paths=[]
    sample=transactions.groupby(["location_id", "date"]).size().iloc[0]
    fig,ax=plt.subplots(figsize=(8,4)); ax.axis("off"); ax.text(.15,.5,"\n".join(["transaction row"]*sample),ha="center",va="center",bbox={"boxstyle":"round","facecolor":"#dbeafe"}); ax.annotate("group by\nlocation + date",(.55,.5),(.35,.5),arrowprops={"arrowstyle":"->"},ha="center"); ax.text(.82,.5,"one location-day row",ha="center",va="center",bbox={"boxstyle":"round","facecolor":"#dcfce7"}); ax.set_title("Aggregation changes grain deliberately"); paths.append(_save(fig,output_dir/"chapter-12-grain-transformation.png"))
    ordered=summary.sort_values("location_name"); fig,(a,b)=plt.subplots(1,2,figsize=(10,4)); a.bar(ordered.location_name,ordered.revenue); a.set(ylabel="revenue ($)",title="Revenue"); b.bar(ordered.location_name,ordered.labor_hours,color="tab:orange"); b.set(ylabel="labor hours",title="Labor input"); [x.tick_params(axis="x",rotation=25) for x in (a,b)]; paths.append(_save(fig,output_dir/"chapter-12-revenue-and-labor.png"))
    fig,ax=plt.subplots(figsize=(8,4)); ax.bar(ordered.location_name,ordered.revenue_per_labor_hour,color="tab:green"); ax.set(title="Revenue per labor hour by location",ylabel="revenue per labor hour ($/hour)"); ax.tick_params(axis="x",rotation=25); paths.append(_save(fig,output_dir/"chapter-12-revenue-per-labor-hour.png"))
    return paths


def run(output_dir: Path | None = None) -> int:
    """Run the grain -> keys -> join -> validate Chapter 12 experiment."""
    transactions, locations, labor = load_chapter_12_data(); validate_source_keys(transactions, locations, labor)
    attached, unmatched = attach_locations(transactions, locations)
    repeated, inflated = demonstrate_labor_duplication(transactions, labor)
    daily_revenue = aggregate_daily_revenue(transactions); daily = build_daily_metrics(daily_revenue, labor)
    summary = aggregate_locations(daily, locations); checks = reconcile(transactions, labor, daily, summary)
    if not all(checks.values()): raise AssertionError(checks)
    combinations=many_to_many_example(); paths=create_figures(transactions,daily,summary,output_dir or PROJECT_ROOT/"figures")
    print("Chapter 12 — Transform, Group & Join | grain → keys → aggregate → join → validate → interpret")
    print(f"transactions {transactions.shape}: one row = one transaction; locations {locations.shape}: one row = one location; labor_daily {labor.shape}: one row = one location-day")
    print(f"Keys valid: transaction_id unique; location_id unique in locations; (location_id, date) unique in labor. Metadata join rows {len(transactions)} → {len(attached)}; unmatched={unmatched}.")
    print(f"Deliberate bad join: {len(transactions)} transaction rows repeat daily labor; naive labor={inflated:.1f} vs actual={labor.labor_hours.sum():.1f} hours (not a business increase).")
    print(f"Safe workflow: transactions → {len(daily_revenue)} location-days; one-to-one daily join → {len(daily)} rows; location summary → {len(summary)} rows.")
    print("Reconciliation passed: revenue and labor totals agree across compatible grains.")
    print(f"Many-to-many demonstration: 2 orders × 2 campaigns = {len(combinations)} combinations.")
    print(summary[["location_name","revenue","labor_hours","revenue_per_labor_hour"]].round(2).to_string(index=False))
    print(f"Figures generated={len(paths)}. Interpretation: the rate describes revenue relative to labor input, not service quality, profitability, capacity, labor mix, or demand conditions.")
    return 0
